### ISSUE TITLE
Overview & tracking

### ISSUE THREAD

**Issue by bjornwgnr** [substrate-developer-hub/substrate-developer-hub.github.io#1]
(data merged with [#578](https://github.com/paritytech/substrate/issues/578))  cc/ @0x7CFE 

Priority: `P1`, `P2`, `P3`

## TOPBAR

[Ask a question](https://substrate.readme.io/discuss) [either links to on-hub discussion section or [stackoverflow](https://stackoverflow.com/questions/ask?tags=substrate]
[Chat with us](https://riot.im/app/#/room/!HzySYSaIhtyWrwiwEV:matrix.org)

## Home `P2`

- How to get Substrate
- 10,000ft view on Substrate
- Link to parity.io/substrate
- How to Contribute: github.com/paritytech/substrate#contributing
- How to report an issue or provide feedback:  github.com/paritytech/substrate/issues
- [Discuss your project on Parity's Forum](http://forum.parity.io/c/substrate)
- Bug Bounty Program: https://www.parity.io/bug-bounty
- Missing a Feature? Check out our roadmap on GH/ announcements (parity.io/blog)
- Community:
    - [StackOverflow](https://stackoverflow.com/questions/tagged/substrate) // [Ask a question](https://stackoverflow.com/questions/ask?tags=substrate)
    - Follow us: Twitter, Reddit, Github

## Introduction `P1/P2`

1. What is Substrate -> condense https://medium.com/paritytech/what-is-substrate-29af4231d7e0 `P1`
2. How it works - wasm runtime + rust environment `P1`
3. When to use and not use Substrate? `P2`
    * How to decide, what should be implemented in runtime and what not
    * What parts are optional and what parts are expected to be implemented by the user
4. What parts are optional and what parts are expected to be implemented by the user

## Examples `P1`

1. [Recipes (reorganize)](https://substrate.readme.io/docs/substrate-runtime-recipes)

2. Sample Apps & Runtimes
    - [x] ERC20 - @gautamdhameja 
    - [x] ERC721 - @shawntabrizi 
    - [x] TCR - @gautamdhameja
    - [x] CryptoKitties - @shawntabrizi

3. UI Interaction Patterns

## Concepts `P2`

1. Architecture
    - [ ] How runtime interacts with the outer code
    - [ ] Asynchronous model, futures, tasks, etc as it is used in the Substrate
    - [x] Lifecycle of a transaction from network to storage, how a block is imported - @joepetrowski
    - [ ] `entry points`
    - [ ] `consensus`
    - [ ] `executor`
    - [ ] `network`
    - [ ] `runtime`
    - [ ] `service`
3. [Substrate primitives & core data types](https://substrate.readme.io/docs/what-is-substrate#section-core-datatypes)
4. Layers of abstraction - bare bones, runtime modules (SRML), Node
    a. Core (including consensus)
    b. SRML (brief overview of what is SRML)
    c. Substrate Node
1. Compilation - WASM (without std) and rust (with std)
1. Macros & Entry points(Full in-depth coverage of Substrate macros and module entry points)
    - [ ] [`impl_stubs!`](http://wiki.parity.io/impl_stubs)
    - [ ] `construct_runtime!` - @shawntabrizi - [#1288](https://github.com/paritytech/substrate/issues/1288)
    - [ ] `decl_apis!`
    - [ ] [`decl_module!`](https://github.com/paritytech/wiki/pull/272) (WIP by @0x7CFE) - @shawntabrizi - [#1288](https://github.com/paritytech/substrate/issues/1288)
    - [ ] `decl_event!`
    - [ ] [`decl_storage!`](http://wiki.parity.io/decl_storage) - @shawntabrizi - [#1288](https://github.com/paritytech/substrate/issues/1288)
    - [ ] `impl_outer_origin!`
    - [ ] `impl_outer_dispatch!`
    - [ ] `impl_outer_event!`
    - [ ] `impl_outer_inherent!`
    - [ ] `impl_outer_config!`
    - [ ] `impl_outer_log!`
    - [ ] `Call (module level)`
    - [ ] `PrivCall (module level)`
    - [ ] `Call (dispatch level)`
    - [ ] `PrivCall (dispatch level)`
    - [ ] `aux`

## Runtime Tutorials `P1`

1. Quick start (we already have one)
2. Usage
3. Guides
5. Bonds UI
    - When should I use this vs Polkadot UI?
6. Polkadot API + Apps UI
7. Macros
8. Rust Playground
9. Local Node detection, kitty image generation before them creating ui
10. Advanced UTXO Tutorial
11. Production Deployment
12. IPFS
13. Storage Upgrade
14. Node Configuration 
15. Dedicated Front End
16. Upgrade Single Page

## Tutorials for Polkadot `P3`

1. Prerequisites to make your Substrate chain compatible with Polkadot
2. Porting your Substrate chain to Polkadot (parachain)
3. Bridging your Substrate chain to Polkadot
4. Inter-chain communication

### API

[Overview of Substrate API](https://substrate.readme.io/docs/runtime-and-api).

### CLI

Overview of the Substrate CLI (commands and scripts)

### SRML

In-depth overview of each SRML module that ships with Substrate

- [ ] `example` (see this first)
- [ ] [`assets`](https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Assets-Module) - @ltfschoen
- [x] `balances`
- [x] `consensus`
- [x] `contract`
- [ ] [`council`](https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Council-Module) - @ltfschoen 
- [ ] [`democracy`](https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Democracy-Module) - @ltfschoen
- [ ] [`session`](https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Session-Module) - @ltfschoen
- [x] [`staking`](https://hackmd.io/nr6kPD2sR4urmljtvHs0CQ?view#Staking-Module) - @ltfschoen
- [x] `timestamp`
- [ ] `treasury`
- [ ] `How to build your own SRML module`

### Primitives (Types and Traits)

- [ ] `*::Trait`
- [ ] `*::Service`
- [ ] `HasPublicAux`
- [ ] `bft::Environment`
- [ ] `bft::Proposer`
- [ ] `BlockBuilder`
- [ ] `Specialization<B>`
- [ ] `Encode` / `Decode` (Codec)
- [ ] `Executive`

### Glossary
- [x] [Glossary](https://substrate.readme.io/docs/glossary)

### Documentation from code-comments (RUSTDOCS) `wait for release on docs.rs`
Not-released yet: https://crates.parity.io/substrate_service/index.html

## FAQ
`Generated from questions in the discussion section or custom FAQ`
https://substrate.readme.io/discuss?isFAQ=true

## Changelog/Release notes `P2`

- initially just link to GH release page
