### ISSUE TITLE
Figure out the Versioning Story

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#118]
We have Substrate v1.0 now, Substrate v2.0 coming soon, and always Substrate latest/master.

This involves some needed magic around reference documentation, search indexing, clarity to the user, etc...

While it is probably not super important at the time of writing this issue, it is something that we should think about in the long term.

**Task Updated:**
- [x] Enable versioning for source and translated doc.
- [ ] Fix search between different version.
- [ ] Correct links to reference doc in different versions.

**Comment by kaichaosun** [comment]
The translations may also need version management in the future, I haven't seen any use cases for now, let's keep this thread to discuss and track it.

**Comment by JoshOrndorff** [comment]
For reference docusaurus docs on versioning https://docusaurus.io/docs/en/versioning

@kaichaosun There is a [short paragraph](https://docusaurus.io/docs/en/versioning#versioning-and-translations) about versioning with translation at the end.

We can restrict search results to current version [like we did with current language](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/commit/f07250879d6917887df24dd5aeda6ea6f0a9e030).
But I will say, that restriction seems to be interfering with our search results for non-docusaurus portions of the site.

**Comment by JoshOrndorff** [comment]
Further evidence that we're ready to start versioning the docs. https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/156

**Comment by JoshOrndorff** [comment]
Docusaurus has a nice [versioning fallback feature](https://docusaurus.io/docs/en/versioning#fallback-functionality) such that if you request version 3.0 of a document, but that doc hasn't changed since 1.0, it will automatically serve the 1.0 version of the doc. The only problem is that we're in a situation where we don't yet have full documentation coverage.

**Proposal**
We cut version 1.0.0 soonish (like maybe end of July 2019). This will essentially copy the current docs into a folder called `docs/1.0.0`. From then until we decide otherwise, we write docs in a v1-first fashion:

* Changes specific to v1.0 go in the `docs/1.0.0` folder
* Changes specific to master go directly in the `docs` directory
* Additions go in _both_ directories
* Additions that _do not_ apply to both branches _still_ go in both directories. In this case you have two sub-options.
  * Write two versions (one for master and one for v1)
  * Write against v1, and open an issue to update the v1 version to match master.

At some point in the future we decide to switch to a master-first style.

Thoughts @kaichaosun @shawntabrizi @joepetrowski  ?

**Comment by shawntabrizi** [comment]
I think a master first style is the wrong approach since master will likely always be breaking more often than our latest "stable" version.

I think we can move things into a 1.0.0 folder ASAP, why wait until July?

**Comment by JoshOrndorff** [comment]
> master will likely always be breaking more often than our latest "stable" version.

Fair. I've crossed that out of my proposal

> I think we can move things into a 1.0.0 folder ASAP, why wait until July?

I'm fine with doing it asap, which is why I opened the PR already. One reason we _might_ want to wait is because we're currently missing several docs entirely. If we cut the version now, then when we go back and add missing docs, we have to add them in two places (`docs` and `docs/v1.0.0`). That's definitely not prohibitive, just a minor pain.

@kaichaosun and I will get the translation versioning set and review our work together Friday.
