### ISSUE TITLE
Compose Substrate dev resources in Chinese.

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-developer-hub.github.io#84]
There are very rare dev resources in Chinese, also lack an entry point for local dev to get started. 
I feel like we need to do something to improve the above situation. This is my current plan:
* [x] Setup local dev portal in one of the top media platforms 👉 [zhihu](https://zhuanlan.zhihu.com/substrate).
* [x] Translate [awesome-substrate](https://github.com/nczhu/awesome-substrate) 👉 [PR](https://github.com/nczhu/awesome-substrate/pull/5).
* [x] Compose a post for using Substrate to build first blockchain, leverage this [doc](https://docs.substrate.dev/docs/deploying-a-substrate-node-chain) 👉 [post](https://zhuanlan.zhihu.com/p/67580341)
* [ ] Compose a post to build a customized blockchain, [kitty](https://shawntabrizi.com/substrate-collectables-workshop/#/) or [real estate](https://github.com/kaichaosun/substrate-real-estate-node), TBD.
* [ ] Collect feedbacks from devs that are using Substrate.

**Comment by JoshOrndorff** [comment]
Hi @kaichaosun 
Great work so far, and thanks for helping out. I want to let you know that I'm working on migrating the "substrate developers hub" to the [docusaurus](http://docusaurus.io/) platform. That platform supports multiple languages. Would you be interested in hosting some of your chinese-language work there after the migration?

**Comment by kaichaosun** [comment]
Hi, @JoshOrndorff,  this sounds a good idea, will do that after the migration.

**Comment by kaichaosun** [comment]
@JoshOrndorff, before we enable the translations in circleci, I'm wondering which email account should we use to setup Crowdin account? I suggest to use a parity shared account like substrate-developer-hub@parity.com. Then the registration information of Crowdin like password can be put in a secrect sharing tool.

**Comment by kaichaosun** [comment]
**Summary about how to do the localization:**
[doc](https://hackmd.io/@2dHpJQYgQrCqfxqXMtJTFQ/B1f6WH8A4)

**TODO:**
- [x] Enable translation and localization in Docusaurus
- [ ] Create Crowndin project with the proper account, it should be the admin of this repo, better not to use a personal account.
- [ ] Integrate with CI, blocked by Crowndin account creation.
- [ ] Discuss around version control.

**Comment by JoshOrndorff** [comment]
@kaichaosun It seems the Chinese docs pages don't load properly. 

1. Start the server with `yarn start` 
2. Navigate to `http://localhost:3000/docs/en/quickstart/getting-started`
3. Select `中文` which takes you to `http://localhost:3000/docs/zh-CN/quickstart/getting-started`
4. See the error `Cannot GET /docs/zh-CN/quickstart/getting-started`

I'm guessing you already know that, but wanted to report it just in case.

Regarding what account to use, I had the same curiosity when I was setting up circleCI. The commits come from a [non-account](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/tree/master). What would it take to get crowdin set up? An actual email address? A github acocunt/?

**Comment by kaichaosun** [comment]
* The 404 error for Chinese doc' links is awarded. I'm considering do we want to disable the `中文` for now, and enable it once the Chinese docs are ready.
* Crowdin setup can be made with an email or through a Github account.

**Comment by shawntabrizi** [comment]
@kaichaosun Can we reopen the remaining items as new issues and close this one? Seems like our migration to Docusaurus is pretty much done.

**Comment by kaichaosun** [comment]
Sure, will do that.
